
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        C:/src/get_aoc_input/bin/CMakeFiles/3.28.0/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/LLVM/bin/clang++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        C:/src/get_aoc_input/bin/CMakeFiles/3.28.0/CompilerIdCXX/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-sd4vzc"
      binary: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-sd4vzc"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-sd4vzc'
        
        Run Build Command(s): C:/DEVELO~1/ninja/bin/ninja.exe -v cmTC_22eeb
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\clang.exe -DCMAKE_INTDIR=\\"Debug\\"  -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles/cmTC_22eeb.dir/Debug/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_22eeb.dir\\Debug\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_22eeb.dir/Debug/CMakeCCompilerABI.c.obj -c "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeCCompilerABI.c"
        [2/2] C:\\windows\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console CMakeFiles/cmTC_22eeb.dir/Debug/CMakeCCompilerABI.c.obj -o Debug\\cmTC_22eeb.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:Debug\\cmTC_22eeb.lib -Xlinker /pdb:Debug\\cmTC_22eeb.pdb -Xlinker /version:0.0     && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-fcoy97"
      binary: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-fcoy97"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-fcoy97'
        
        Run Build Command(s): C:/DEVELO~1/ninja/bin/ninja.exe -v cmTC_1d1c3
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -DCMAKE_INTDIR=\\"Debug\\"  -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles/cmTC_1d1c3.dir/Debug/CMakeCXXCompilerABI.cpp.obj -MF CMakeFiles\\cmTC_1d1c3.dir\\Debug\\CMakeCXXCompilerABI.cpp.obj.d -o CMakeFiles/cmTC_1d1c3.dir/Debug/CMakeCXXCompilerABI.cpp.obj -c "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeCXXCompilerABI.cpp"
        [2/2] C:\\windows\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console CMakeFiles/cmTC_1d1c3.dir/Debug/CMakeCXXCompilerABI.cpp.obj -o Debug\\cmTC_1d1c3.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:Debug\\cmTC_1d1c3.lib -Xlinker /pdb:Debug\\cmTC_1d1c3.pdb -Xlinker /version:0.0     && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Internal/FeatureTesting.cmake:84 (_record_compiler_features)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Compiler/CMakeCommonCompilerMacros.cmake:121 (_record_compiler_features_cxx)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-2olbl5"
      binary: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-2olbl5"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: 'C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-2olbl5'
        
        Run Build Command(s): C:/DEVELO~1/ninja/bin/ninja.exe -v cmTC_440cc
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -DCMAKE_INTDIR=\\"Debug\\"  -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview   -std=c++14 -MD -MT CMakeFiles/cmTC_440cc.dir/Debug/feature_tests.cxx.obj -MF CMakeFiles\\cmTC_440cc.dir\\Debug\\feature_tests.cxx.obj.d -o CMakeFiles/cmTC_440cc.dir/Debug/feature_tests.cxx.obj -c C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-2olbl5/feature_tests.cxx
        [2/2] C:\\windows\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console CMakeFiles/cmTC_440cc.dir/Debug/feature_tests.cxx.obj -o Debug\\cmTC_440cc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:Debug\\cmTC_440cc.lib -Xlinker /pdb:Debug\\cmTC_440cc.pdb -Xlinker /version:0.0   -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Internal/FeatureTesting.cmake:34 (try_compile)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Internal/FeatureTesting.cmake:84 (_record_compiler_features)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/Compiler/CMakeCommonCompilerMacros.cmake:129 (_record_compiler_features_cxx)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeDetermineCompileFeatures.cmake:70 (cmake_record_cxx_compile_features)"
      - "C:/Developer Tools/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:70 (CMAKE_DETERMINE_COMPILE_FEATURES)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compile features"
    directories:
      source: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-y630sb"
      binary: "C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-y630sb"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/Program Files/LLVM/bin/clang-scan-deps.exe"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_FEATURE_TEST"
      cached: true
      stdout: |
        Change Dir: 'C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-y630sb'
        
        Run Build Command(s): C:/DEVELO~1/ninja/bin/ninja.exe -v cmTC_c9059
        [1/2] C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -DCMAKE_INTDIR=\\"Debug\\"  -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview   -std=c++14 -MD -MT CMakeFiles/cmTC_c9059.dir/Debug/feature_tests.cxx.obj -MF CMakeFiles\\cmTC_c9059.dir\\Debug\\feature_tests.cxx.obj.d -o CMakeFiles/cmTC_c9059.dir/Debug/feature_tests.cxx.obj -c C:/src/get_aoc_input/bin/CMakeFiles/CMakeScratch/TryCompile-y630sb/feature_tests.cxx
        [2/2] C:\\windows\\system32\\cmd.exe /C "cd . && C:\\PROGRA~1\\LLVM\\bin\\CLANG_~1.EXE -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console CMakeFiles/cmTC_c9059.dir/Debug/feature_tests.cxx.obj -o Debug\\cmTC_c9059.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:Debug\\cmTC_c9059.lib -Xlinker /pdb:Debug\\cmTC_c9059.pdb -Xlinker /version:0.0   -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames  && cd ."
        
      exitCode: 0
...
